local mapping_new = {
  { "<leader> ",     desc = "Telescope",                                       nowait = false,                        remap = false },
  { "<leader>/",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>0",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>0..9",  desc = "Switch buffers",                                  nowait = false,                        remap = false },
  { "<leader>1",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>2",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>3",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>4",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>5",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>6",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>7",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>8",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>9",     hidden = true,                                            nowait = false,                        remap = false },
  { "<leader><F9>",  hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>H",     group = "HELP",                                           nowait = false,                        remap = false },
  { "<leader>HC",    desc = "FZF Colors Left",                                 nowait = false,                        remap = false },
  { "<leader>Hz",    desc = "Describe Face",                                   nowait = false,                        remap = false },
  { "<leader>M",     desc = "Maximizer Toggle",                                nowait = false,                        remap = false },
  { "<leader>T",     group = "TABS",                                           nowait = false,                        remap = false },
  { "<leader>TN",    desc = "New",                                             nowait = false,                        remap = false },
  { "<leader>Tab",   desc = "Alternate Buffer",                                nowait = false,                        remap = false },
  { "<leader>Tc",    desc = "Close",                                           nowait = false,                        remap = false },
  { "<leader>Tn",    desc = "Next",                                            nowait = false,                        remap = false },
  { "<leader>Tp",    desc = "Previous",                                        nowait = false,                        remap = false },
  { "<leader>Y",     desc = "Paste from clipboard",                            nowait = false,                        remap = false },
  { "<leader>a",     desc = "ACTIONS",                                         nowait = false,                        remap = false },
  { "<leader>b",     desc = "+BUFFERS",                                        nowait = false,                        remap = false },
  { "<leader>c",     group = "CODE",                                           nowait = false,                        remap = false },
  { "<leader>cF",    desc = "Fix Selcted",                                     nowait = false,                        remap = false },
  { "<leader>ca",    desc = "Code Actions",                                    nowait = false,                        remap = false },
  { "<leader>cc",    "<cmd>CocInfo<cr>",                                       desc = "Coc Info",                     nowait = false, remap = false },
  { "<leader>ce",    desc = "Hide Float",                                      nowait = false,                        remap = false },
  { "<leader>cg",    group = "git",                                            nowait = false,                        remap = false },
  { "<leader>cgc",   desc = "Commits",                                         nowait = false,                        remap = false },
  { "<leader>cgd",   desc = "Diff Cached",                                     nowait = false,                        remap = false },
  { "<leader>cgf",   desc = "Fold Unchanged",                                  nowait = false,                        remap = false },
  { "<leader>cgi",   desc = "Hunk Info",                                       nowait = false,                        remap = false },
  { "<leader>cgs",   desc = "Show Commits",                                    nowait = false,                        remap = false },
  { "<leader>cgt",   desc = "Toggle Gutters",                                  nowait = false,                        remap = false },
  { "<leader>cgu",   desc = "Hunk Undo",                                       nowait = false,                        remap = false },
  { "<leader>co",    desc = "Code Actions",                                    nowait = false,                        remap = false },
  { "<leader>cu",    desc = "Coc Update",                                      nowait = false,                        remap = false },
  { "<leader>d",     group = "DEBUG",                                          nowait = false,                        remap = false },
  { "<leader>e",     group = "DIAGNOSTIC",                                     nowait = false,                        remap = false },
  { "<leader>el",    desc = "Coc Diagnostic",                                  nowait = false,                        remap = false },
  { "<leader>f",     group = "FILE",                                           nowait = false,                        remap = false },
  { "<leader>fn",    "<cmd>enew<cr>",                                          desc = "New File",                     nowait = false, remap = false },
  { "<leader>g",     group = "GIT",                                            nowait = false,                        remap = false },
  { "<leader>g2",    ":diffget //2",                                           desc = "Get Left",                     nowait = false, remap = false },
  { "<leader>g3",    ":Gvdiffsplit!",                                          desc = "Split 3 W",                    nowait = false, remap = false },
  { "<leader>gF",    desc = "FZF git files preview",                           nowait = false,                        remap = false },
  { "<leader>gP",    desc = "GIT PUSH",                                        nowait = false,                        remap = false },
  { "<leader>gR",    "<cmd>GV?<cr>",                                           desc = "Commit Browser(LocationList)", nowait = false, remap = false },
  { "<leader>gb",    "<cmd>Git blame<cr>",                                     desc = "blame",                        nowait = false, remap = false },
  { "<leader>gc",    desc = "FZF Git Commits",                                 nowait = false,                        remap = false },
  { "<leader>gm",    desc = "Git Messenger Popup",                             nowait = false,                        remap = false },
  { "<leader>gr",    "<cmd>GV<cr>",                                            desc = "Commit Browser",               nowait = false, remap = false },
  { "<leader>gt",    "<cmd>GV!<cr>",                                           desc = "Commit Browser(Current)",      nowait = false, remap = false },
  { "<leader>gu",    ":diffget //3",                                           desc = "Get Right",                    nowait = false, remap = false },
  { "<leader>h",     group = "HIGHLIGHT",                                      nowait = false,                        remap = false },
  { "<leader>hh",    desc = "Toggle Search Highlight",                         nowait = false,                        remap = false },
  { "<leader>i",     desc = "Files...",                                        nowait = false,                        remap = false },
  { "<leader>j",     group = "JUMP",                                           nowait = false,                        remap = false },
  { "<leader>l",     "<cmd>Buffers<cr>",                                       desc = "Buffers...",                   nowait = false, remap = false },
  { "<leader>o",     group = "CUSTOM",                                         nowait = false,                        remap = false },
  { "<leader>oA",    desc = "ISwap Previous Inner",                            nowait = false,                        remap = false },
  { "<leader>oF",    desc = "fold",                                            nowait = false,                        remap = false },
  { "<leader>oa",    desc = "ISwap Next Inner",                                nowait = false,                        remap = false },
  { "<leader>of",    desc = "format",                                          nowait = false,                        remap = false },
  { "<leader>ol",    desc = "js-console.log",                                  nowait = false,                        remap = false },
  { "<leader>oo",    desc = "organize import",                                 nowait = false,                        remap = false },
  { "<leader>op",    desc = "language log",                                    nowait = false,                        remap = false },
  { "<leader>os",    desc = "ISwap",                                           nowait = false,                        remap = false },
  { "<leader>ow",    desc = "ISwapWith",                                       nowait = false,                        remap = false },
  { "<leader>p",     group = "PROJECT",                                        nowait = false,                        remap = false },
  { "<leader>pS",    desc = "Add Session",                                     nowait = false,                        remap = false },
  { "<leader>po",    desc = "toggle explorer",                                 nowait = false,                        remap = false },
  { "<leader>pp",    desc = "Projects",                                        nowait = false,                        remap = false },
  { "<leader>ps",    desc = "Sessions",                                        nowait = false,                        remap = false },
  { "<leader>q",     group = "LIST",                                           nowait = false,                        remap = false },
  { "<leader>qn",    "<cmd>cprev",                                             desc = "Prev QuickList Item",          nowait = false, remap = false },
  { "<leader>qp",    "<cmd>cnext",                                             desc = "Next QuickList Item",          nowait = false, remap = false },
  { "<leader>qq",    "<cmd>ToggleQuickFixWindow<cr>",                          desc = "Toggle QuickList",             nowait = false, remap = false },
  { "<leader>qx",    "<cmd>ClearQuickFixList<cr>",                             desc = "Clear QuickList",              nowait = false, remap = false },
  { "<leader>r",     group = "REPLACE",                                        nowait = false,                        remap = false },
  { "<leader>s",     group = "SEARCH",                                         nowait = false,                        remap = false },
  { "<leader>sv",    desc = "Spectre Open",                                    nowait = false,                        remap = false },
  { "<leader>t",     group = "TESTS",                                          nowait = false,                        remap = false },
  { "<leader>tc",    group = "Coverage",                                       nowait = false,                        remap = false },
  { "<leader>u",     desc = "Diagnostic Info",                                 nowait = false,                        remap = false },
  { "<leader>v",     group = "VISUAL",                                         nowait = false,                        remap = false },
  { "<leader>vs",    group = "SANDWICH",                                       nowait = false,                        remap = false },
  { "<leader>vsa",   desc = "Add...",                                          nowait = false,                        remap = false },
  { "<leader>vsd",   desc = "Delete...",                                       nowait = false,                        remap = false },
  { "<leader>vsr",   desc = "Replace...",                                      nowait = false,                        remap = false },
  { "<leader>w",     group = "WINDOWS",                                        nowait = false,                        remap = false },
  { "<leader>w-",    "<C-W>s",                                                 desc = "split-window-below",           nowait = false, remap = false },
  { "<leader>w1",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w1..7", desc = "Switch Windows",                                  nowait = false,                        remap = false },
  { "<leader>w2",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w3",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w4",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w5",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w6",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w7",    hidden = true,                                            nowait = false,                        remap = false },
  { "<leader>w;",    desc = "VimWin",                                          nowait = false,                        remap = false },
  { "<leader>w=",    "<C-W>=",                                                 desc = "balance-window",               nowait = false, remap = false },
  { "<leader>w?",    "Windows",                                                desc = "fzf-window",                   nowait = false, remap = false },
  { "<leader>wH",    "<C-W>5<",                                                desc = "expand-window-left",           nowait = false, remap = false },
  { "<leader>wJ",    "<cdm>resize +5",                                         desc = "expand-window-below",          nowait = false, remap = false },
  { "<leader>wK",    "<cdm>resize -5",                                         desc = "expand-window-up",             nowait = false, remap = false },
  { "<leader>wL",    "<C-W>5>",                                                desc = "expand-window-right",          nowait = false, remap = false },
  { "<leader>wQ",    desc = "exit",                                            nowait = false,                        remap = false },
  { "<leader>wd",    "<C-W>c",                                                 desc = "delete-window",                nowait = false, remap = false },
  { "<leader>we",    "<C-W>v",                                                 desc = "split-window-right",           nowait = false, remap = false },
  { "<leader>wh",    "<C-W>h",                                                 desc = "window-left",                  nowait = false, remap = false },
  { "<leader>wj",    "<C-W>j",                                                 desc = "window-below",                 nowait = false, remap = false },
  { "<leader>wk",    "<C-W>k",                                                 desc = "window-up",                    nowait = false, remap = false },
  { "<leader>wl",    "<C-W>l",                                                 desc = "window-right",                 nowait = false, remap = false },
  { "<leader>wm",    group = "zoom",                                           nowait = false,                        remap = false },
  { "<leader>wmi",   desc = "zoom-in",                                         nowait = false,                        remap = false },
  { "<leader>wmm",   desc = "zoom",                                            nowait = false,                        remap = false },
  { "<leader>wmo",   desc = "zoom-out",                                        nowait = false,                        remap = false },
  { "<leader>wq",    "<C-W>c",                                                 desc = "delete-window",                nowait = false, remap = false },
  { "<leader>ws",    "<C-W>s",                                                 desc = "split-window-below",           nowait = false, remap = false },
  { "<leader>wv",    "<C-W>v",                                                 desc = "split-window-below",           nowait = false, remap = false },
  { "<leader>ww",    "<C-W>c",                                                 desc = "delete-window",                nowait = false, remap = false },
  { "<leader>w|",    "<C-W>v",                                                 desc = "split-window-right",           nowait = false, remap = false },
  { "<leader>x",     group = "CODE-EXTRA",                                     nowait = false,                        remap = false },
  { "<leader>xj",    "<CMD>TSJJoin<cr>",                                       desc = "Join",                         nowait = false, remap = false },
  { "<leader>xo",    desc = "New Line In Normal Mode",                         nowait = false,                        remap = false },
  { "<leader>xr",    desc = "Replace Under Caret",                             nowait = false,                        remap = false },
  { "<leader>xs",    "<CMD>TSJSplit<cr>",                                      desc = "Split",                        nowait = false, remap = false },
  { "<leader>xt",    "<CMD>TSJToggle<cr>",                                     desc = "Toggle",                       nowait = false, remap = false },
  { "<leader>y",     desc = "Copy to clipboard",                               nowait = false,                        remap = false },
  { "<leader>z",     group = "SEARCH IN BUFFER",                               nowait = false,                        remap = false },
  { "<leader>z/",    desc = "Incsearch-f",                                     nowait = false,                        remap = false },
  { "<leader>z?",    desc = "incsearch-j",                                     nowait = false,                        remap = false },
  { "<leader>zf",    group = "FUZZY",                                          nowait = false,                        remap = false },
  { "<leader>zf/",   desc = "incsearch-fuzzy-/",                               nowait = false,                        remap = false },
  { "<leader>zf?",   desc = "incsearch-fuzzy-?",                               nowait = false,                        remap = false },
  { "<leader>zff",   desc = "incsearch-fuzzy-stay",                            nowait = false,                        remap = false },
  { "<leader>zi",    '<cmd>set noignorecase! | echo "Changed ignorecase"<cr>', desc = "Toggle Ignorecase",            nowait = false, remap = false },
  { "<leader>zz",    desc = "insearch-stay",                                   nowait = false,                        remap = false },
}
-- local mappings = {
--   ["<leader>"] = {
--     a = { "ACTIONS" },
--     b = { "+BUFFERS" },
--     c = {
--       name = "+CODE",
--       a = { "Code Actions" },
--       o = { "Code Actions" },
--       c = { "<cmd>CocInfo<cr>", "Coc Info" },
--       e = { "Hide Float" },
--       F = { "Fix Selcted" },
--       u = { "Coc Update" },
--       g = {
--         name = "git",
--         c = "Commits",
--         i = "Hunk Info",
--         u = "Hunk Undo",
--         f = "Fold Unchanged",
--         d = "Diff Cached",
--         s = "Show Commits",
--         t = "Toggle Gutters",
--       },
--     },
--     e = {
--       name = "+DIAGNOSTIC",
--       l = "Coc Diagnostic",
--     },
--     d = { name = "+DEBUG" },
--     g = {
--       name = "+GIT",
--       ["3"] = { ":Gvdiffsplit!", "Split 3 W" },
--       ["2"] = { ":diffget //2", "Get Left" },
--       ["u"] = { ":diffget //3", "Get Right" },
--       b = { "<cmd>Git blame<cr>", "blame" },
--       c = { "FZF Git Commits" },
--       -- n = { "<cmd>VGit actions<cr>", "VGIT" },
--       m = { "Git Messenger Popup" },
--       F = { "FZF git files preview" },
--       P = { "GIT PUSH" },
--       r = { "<cmd>GV<cr>", "Commit Browser" },
--       t = { "<cmd>GV!<cr>", "Commit Browser(Current)" },
--       R = { "<cmd>GV?<cr>", "Commit Browser(LocationList)" },
--     },
--     h = {
--       name = "+HIGHLIGHT",
--       h = "Toggle Search Highlight",
--     },
--     H = {
--       name = "+HELP",
--       C = { 'FZF Colors Left' },
--       z = { 'Describe Face' },
--     },
--     i = { "Files..." },
--     l = { "<cmd>Buffers<cr>", "Buffers..." },
--     o = {
--       name = "+CUSTOM",
--       a = { "ISwap Next Inner" },
--       A = { "ISwap Previous Inner" },
--       s = { "ISwap" },
--       w = { "ISwapWith" },
--       l = { "js-console.log" },
--       p = { "language log" },
--       o = { "organize import" },
--       f = { "format" },
--       F = { "fold" },
--     },
--     p = {
--       name = '+PROJECT',
--       S = 'Add Session',
--       p = 'Projects',
--       o = 'toggle explorer',
--       s = 'Sessions',
--     },
--     q = {
--       name = '+LIST',
--       q = { "<cmd>ToggleQuickFixWindow<cr>", 'Toggle QuickList' },
--       x = { '<cmd>ClearQuickFixList<cr>', "Clear QuickList" },
--       p = { "<cmd>cnext", "Next QuickList Item" },
--       n = { "<cmd>cprev", "Prev QuickList Item" },
--     },
--     r = { name = "+REPLACE" },
--     j = {
--       name = '+JUMP',
--     },
--     u = { "Diagnostic Info" },
--     y = { "Copy to clipboard" },
--     Y = { "Paste from clipboard" },
--     M = { "Maximizer Toggle" },
--     ["Tab"] = { "Alternate Buffer" },
--     ["/"] = { 'which_key_ignore' },
--     ["1"] = { 'which_key_ignore' },
--     ["2"] = { 'which_key_ignore' },
--     ["3"] = { 'which_key_ignore' },
--     ["4"] = { 'which_key_ignore' },
--     ["5"] = { 'which_key_ignore' },
--     ["6"] = { 'which_key_ignore' },
--     ["7"] = { 'which_key_ignore' },
--     ["8"] = { 'which_key_ignore' },
--     ["9"] = { 'which_key_ignore' },
--     ["0"] = { 'which_key_ignore' },
--     ["<F9>"] = { 'which_key_ignore' },
--     ["0..9"] = { "Switch buffers" },
--     [" "] = { "Telescope" },
--     f = {
--       name = "+FILE",
--       -- f = { "Format" },
--       -- r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File" },
--       n = { "<cmd>enew<cr>", "New File" },
--     },
--     s = {
--       name = "+SEARCH",
--       v = "Spectre Open",
--     },
--     t = {
--       name = "+TESTS",
--       c = {
--         name = "+Coverage",
--       }
--     },
--     T = {
--       name = "+TABS",
--       p = "Previous",
--       n = "Next",
--       N = "New",
--       c = "Close",
--     },
--     v = {
--       name = "+VISUAL",
--       s = {
--         name = "+SANDWICH",
--         a = "Add...",
--         d = "Delete...",
--         r = "Replace...",
--       }
--     },
--     x = {
--       name = "+CODE-EXTRA",
--       s = { "<CMD>TSJSplit<cr>", "Split" },
--       j = { "<CMD>TSJJoin<cr>", "Join" },
--       o = { "New Line In Normal Mode" },
--       t = { "<CMD>TSJToggle<cr>", "Toggle" },
--       r = { "Replace Under Caret" }
--     },
--     z = {
--       name = "+SEARCH IN BUFFER",
--       ["/"] = { "Incsearch-f" },
--       ["?"] = { "incsearch-j" },
--       z = { "insearch-stay" },
--       i = { '<cmd>set noignorecase! | echo "Changed ignorecase"<cr>', "Toggle Ignorecase" },
--       f = {
--         name = "+FUZZY",
--         ["/"] = { 'incsearch-fuzzy-/' },
--         ["?"] = { 'incsearch-fuzzy-?' },
--         ["f"] = { 'incsearch-fuzzy-stay' },
--       },
--     },
--     w = {
--       name = "+WINDOWS",
--       ["1..7"] = { "Switch Windows" },
--       ["1"] = { "which_key_ignore" },
--       ["2"] = { "which_key_ignore" },
--       ["3"] = { "which_key_ignore" },
--       ["4"] = { "which_key_ignore" },
--       ["5"] = { "which_key_ignore" },
--       ["6"] = { "which_key_ignore" },
--       ["7"] = { "which_key_ignore" },
--       [";"] = { "VimWin" },
--       ["w"] = { "<C-W>c", "delete-window" },
--       ["e"] = { "<C-W>v", "split-window-right" },
--       ["d"] = { "<C-W>c", "delete-window" },
--       ["-"] = { "<C-W>s", "split-window-below" },
--       ["|"] = { "<C-W>v", "split-window-right" },
--       ["h"] = { "<C-W>h", "window-left" },
--       ["j"] = { "<C-W>j", "window-below" },
--       ["l"] = { "<C-W>l", "window-right" },
--       ["k"] = { "<C-W>k", "window-up" },
--       ["H"] = { "<C-W>5<", "expand-window-left" },
--       ["J"] = { "<cdm>resize +5", "expand-window-below" },
--       ["L"] = { "<C-W>5>", "expand-window-right" },
--       ["K"] = { "<cdm>resize -5", "expand-window-up" },
--       ["="] = { "<C-W>=", "balance-window" },
--       ["q"] = { "<C-W>c", "delete-window" },
--       ["Q"] = { "exit" },
--       ["s"] = { "<C-W>s", "split-window-below" },
--       ["v"] = { "<C-W>v", "split-window-below" },
--       ["?"] = { "Windows", "fzf-window" },
--       ["m"] = {
--         ["name"] = "+zoom",
--         ["m"] = "zoom",
--         ["i"] = "zoom-in",
--         ["o"] = "zoom-out",
--       }
--     },
--   }
-- }
local opts = {
  mode = "n", -- NORMAL mode
  -- prefix: use "<leader>f" for example for mapping everything related to finding files
  -- the prefix is prepended to every mapping part of `mappings`
  prefix = "",
  buffer = nil,   -- Global mappings. Specify a buffer number for buffer local mappings
  silent = true,  -- use `silent` when creating keymaps
  noremap = true, -- use `noremap` when creating keymaps
  nowait = false, -- use `nowait` when creating keymaps
}
local wk = require("which-key")
wk.add(mapping_new, opts)

wk.setup({
  plugins = {
    marks = true,     -- shows a list of your marks on ' and `
    registers = true, -- shows your registers on " in NORMAL or <C-r> in INSERT mode
    -- the presets plugin, adds help for a bunch of default keybindings in Neovim
    -- No actual key bindings are created
    presets = {
      operators = false,                             -- adds help for operators like d, y, ...
      motions = false,                               -- adds help for motions
      text_objects = false,                          -- help for text objects triggered after entering an operator
      windows = false,                               -- default bindings on <c-w>
      nav = false,                                   -- misc bindings to work with windows
      z = false,                                     -- bindings for folds, spelling and others prefixed with z
      g = false,                                     -- bindings for prefixed with g
    },
    spelling = { enabled = true, suggestions = 20 }, -- use which-key for spelling hints
  },
  win = { border = 'single' }
})
